// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgBi5enEKJjQHV1ACVWrMQ_BHACfIyCs8',
    appId: '1:727353165979:web:2aa19ab788524fd4e2de3e',
    messagingSenderId: '727353165979',
    projectId: 'tapn-nmaps-test',
    authDomain: 'tapn-nmaps-test.firebaseapp.com',
    storageBucket: 'tapn-nmaps-test.appspot.com',
    measurementId: 'G-FXHZGFT77T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHmK1FzVgFhVwjf4pJnUYXpuCo5bvWX1A',
    appId: '1:727353165979:android:f2745dcbf329e625e2de3e',
    messagingSenderId: '727353165979',
    projectId: 'tapn-nmaps-test',
    storageBucket: 'tapn-nmaps-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB24WjSxGEHyB33xgpVhZpC9oSPj20z7JE',
    appId: '1:727353165979:ios:fc9bc8d58491fb9fe2de3e',
    messagingSenderId: '727353165979',
    projectId: 'tapn-nmaps-test',
    storageBucket: 'tapn-nmaps-test.appspot.com',
    iosBundleId: 'com.renati.tapn.tapnmaps',
  );
}
